# Generated by Django 2.2.6 on 2019-10-28 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('telephone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.CharField(max_length=30)),
                ('date_of_supply', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('amount', models.IntegerField(max_length=10)),
                ('price_per_unit', models.FloatField()),
                ('Purchase_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customermanage.Customer')),
            ],
        ),
    ]
