# Generated by Django 2.2.6 on 2019-11-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customermanage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase_order',
            name='purchase_number',
            field=models.CharField(default=1, max_length=30),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
