# Generated by Django 2.2.6 on 2019-11-03 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customermanage', '0003_auto_20191102_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='date_of_order',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='date_of_supply',
            field=models.DateTimeField(),
        ),
    ]
