# Generated by Django 2.2.6 on 2019-11-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customermanage', '0004_auto_20191103_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='date_of_order',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='date_of_supply',
            field=models.DateField(),
        ),
    ]
